---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myfirstdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: amzad24/prac
      ports:
      - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 9000
...